
FACES_DIR = "faces"
ENCODINGS_FILE = "face_encodings.pkl"
TRAINING_DATA_FILE = "training_data.pkl"

CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

FACE_RECOGNITION_TOLERANCE = 0.5
FACE_DETECTION_MODEL = "hog"
FACE_DETECTION_UPSAMPLING = 0
MIN_FACE_SIZE = (30, 30)

CONFIDENCE_VOTING_THRESHOLD = 0.65
RECOGNITION_THRESHOLD = 0.4
FACE_MATCH_CONSENSUS = 3
ANTI_SPOOFING_ENABLED = True

GATE_UNLOCK_DURATION = 5
SECURITY_LOCKOUT_ATTEMPTS = 5
LOCKOUT_DURATION = 30

DISPLAY_PREVIEW = True
WINDOW_NAME = "GateGuardian - Advanced Face Recognition"
SHOW_CONFIDENCE_SCORES = True
SHOW_FPS = True

COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_BLUE = (255, 0, 0)
COLOR_YELLOW = (0, 255, 255)
COLOR_ORANGE = (0, 165, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)

BLUR_DETECTION_THRESHOLD = 80  # Lowered for better acceptance
BRIGHTNESS_THRESHOLD = (40, 220)  # Slightly adjusted range
ENABLE_FACE_ALIGNMENT = False  # Disabled to prevent errors
ENABLE_QUALITY_FILTERING = True

ENCODINGS_PER_PERSON = 5
ENABLE_ENSEMBLE_VOTING = True
